# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('data', 'data'),
        ('src/ui/styles.py', 'src/ui'),
    ],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'httpx',
        'openai',
        'yaml',
        'pytest',
        'allure',
        'ui',
        'ui.main_window',
        'ui.pages',
        'ui.pages.base_page',
        'ui.pages.test_case_page',
        'ui.pages.test_script_page',
        'ui.pages.ai_model_page',
        'core',
        'core.test_case_service',
        'core.test_script_service',
        'core.ai_model_service',
        'core.export_service',
        'core.code_validator',
        'models',
        'models.test_case',
        'models.test_script',
        'models.ai_model',
        'models.database',
        'ai',
        'ai.client',
        'ai.prompts',
        'utils',
        'utils.config',
        'utils.logger',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AutoApiTest',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
